line(['$','cd','/']).
line(['$','ls']).
line(['dir','cdnhnmcb']).
line(['dir','dmccnsqv']).
line(['290229','dsm']).
line(['dir','gsszlj']).
line(['dir','hmw']).
line(['dir','jhmrn']).
line(['dir','ncb']).
line(['dir','npclt']).
line(['dir','rvvjbz']).
line(['$','cd','cdnhnmcb']).
line(['$','ls']).
line(['170937','fsjwz.css']).
line(['281758','jmfcfs.gsq']).
line(['109017','jwwv.zlz']).
line(['295735','tsrqvpbq']).
line(['$','cd','..']).
line(['$','cd','dmccnsqv']).
line(['$','ls']).
line(['273438','fsjwz.css']).
line(['dir','jtntzqfd']).
line(['dir','tqmbq']).
line(['211769','vmgpwrbz.nbp']).
line(['205895','wqz.qcg']).
line(['$','cd','jtntzqfd']).
line(['$','ls']).
line(['4635','wqfvvzth.vdz']).
line(['$','cd','..']).
line(['$','cd','tqmbq']).
line(['$','ls']).
line(['dir','bnvspstf']).
line(['22264','bqcvlnw.pmq']).
line(['dir','hwv']).
line(['200690','jlwjsbw.bzf']).
line(['dir','npclt']).
line(['243708','qvnbwvt.sbv']).
line(['157861','tsrqvpbq.mtf']).
line(['$','cd','bnvspstf']).
line(['$','ls']).
line(['46133','mwvz.vwh']).
line(['289236','rjcp.gqj']).
line(['$','cd','..']).
line(['$','cd','hwv']).
line(['$','ls']).
line(['dir','tsrqvpbq']).
line(['$','cd','tsrqvpbq']).
line(['$','ls']).
line(['292872','rvvjbz.mgh']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','npclt']).
line(['$','ls']).
line(['191646','bhllwpr']).
line(['26548','jlwjsbw.bzf']).
line(['214302','nnqz']).
line(['74637','szdjtbt.tmw']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','gsszlj']).
line(['$','ls']).
line(['dir','bjvqcfwc']).
line(['dir','dfzhdhs']).
line(['179837','dsm.hzf']).
line(['112354','gnrzhsw.jcf']).
line(['175236','jlwjsbw.bzf']).
line(['dir','mfnllhfw']).
line(['dir','nwvcgb']).
line(['dir','rvvjbz']).
line(['dir','vcvmq']).
line(['$','cd','bjvqcfwc']).
line(['$','ls']).
line(['125387','rvvjbz']).
line(['$','cd','..']).
line(['$','cd','dfzhdhs']).
line(['$','ls']).
line(['218291','jlwjsbw.bzf']).
line(['dir','jsmjbfg']).
line(['dir','rvvjbz']).
line(['272548','zdrtjvzj.rlt']).
line(['196309','ztdcrnl.hjj']).
line(['$','cd','jsmjbfg']).
line(['$','ls']).
line(['72259','bmszdt']).
line(['242641','fsjwz.css']).
line(['109294','mwtlz']).
line(['149525','sgngzrnn.mww']).
line(['$','cd','..']).
line(['$','cd','rvvjbz']).
line(['$','ls']).
line(['175613','rqjmjhrb']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','mfnllhfw']).
line(['$','ls']).
line(['119986','fcjrv.dvh']).
line(['dir','gwjgjljj']).
line(['157962','jjjbv.fdp']).
line(['dir','mwttp']).
line(['30246','vhzdjv.fqh']).
line(['197554','zdrtjvzj.rlt']).
line(['288875','zhdn.dtj']).
line(['$','cd','gwjgjljj']).
line(['$','ls']).
line(['237890','mlmmfh']).
line(['dir','ncjzqll']).
line(['10935','zdrtjvzj.rlt']).
line(['$','cd','ncjzqll']).
line(['$','ls']).
line(['152092','gwwh.ttt']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','mwttp']).
line(['$','ls']).
line(['217929','fsjwz.css']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','nwvcgb']).
line(['$','ls']).
line(['131410','fsjwz.css']).
line(['dir','nqrdmvjm']).
line(['82487','qwbg.hcb']).
line(['dir','tsrqvpbq']).
line(['123617','tsrqvpbq.wqw']).
line(['$','cd','nqrdmvjm']).
line(['$','ls']).
line(['dir','btjwzz']).
line(['dir','dsm']).
line(['dir','fcrsj']).
line(['141465','fsjwz.css']).
line(['133916','ztdcrnl.hjj']).
line(['$','cd','btjwzz']).
line(['$','ls']).
line(['dir','nqrdmvjm']).
line(['dir','tsrqvpbq']).
line(['150003','zdrtjvzj.rlt']).
line(['$','cd','nqrdmvjm']).
line(['$','ls']).
line(['dir','dsm']).
line(['160109','gzv.wzw']).
line(['33187','mcgmjn.ftg']).
line(['dir','pbgdcwd']).
line(['167821','ztdcrnl.hjj']).
line(['$','cd','dsm']).
line(['$','ls']).
line(['84979','gwwh.ttt']).
line(['dir','rvvjbz']).
line(['$','cd','rvvjbz']).
line(['$','ls']).
line(['189309','btvjmhp.dwm']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','pbgdcwd']).
line(['$','ls']).
line(['240743','rzgbfcg.dzg']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','tsrqvpbq']).
line(['$','ls']).
line(['284223','mmhvjn']).
line(['188341','tnv.rcs']).
line(['271396','zdrtjvzj.rlt']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','dsm']).
line(['$','ls']).
line(['128966','ptf']).
line(['$','cd','..']).
line(['$','cd','fcrsj']).
line(['$','ls']).
line(['261786','qljq.nrv']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','tsrqvpbq']).
line(['$','ls']).
line(['57089','fsjwz.css']).
line(['208087','ttfhpzll']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','rvvjbz']).
line(['$','ls']).
line(['dir','ldglv']).
line(['$','cd','ldglv']).
line(['$','ls']).
line(['39389','wjwzdg.ldb']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','vcvmq']).
line(['$','ls']).
line(['dir','jzgd']).
line(['246541','lmfdrnnz.dcc']).
line(['169613','npclt']).
line(['264902','npclt.jsl']).
line(['dir','pwzbvvwz']).
line(['82651','rch.bsc']).
line(['223282','vddwtwz.pqf']).
line(['dir','wnb']).
line(['$','cd','jzgd']).
line(['$','ls']).
line(['91717','dqmhdw.mjr']).
line(['69771','ztdcrnl.hjj']).
line(['$','cd','..']).
line(['$','cd','pwzbvvwz']).
line(['$','ls']).
line(['dir','cdmfv']).
line(['dir','fvqjbd']).
line(['dir','nhvhhs']).
line(['dir','npclt']).
line(['dir','rgdb']).
line(['$','cd','cdmfv']).
line(['$','ls']).
line(['172054','dsm.qjw']).
line(['$','cd','..']).
line(['$','cd','fvqjbd']).
line(['$','ls']).
line(['212067','hclqv']).
line(['dir','tcjsbn']).
line(['$','cd','tcjsbn']).
line(['$','ls']).
line(['40576','wbzwnc.pqf']).
line(['13447','wlrjhcf.jtg']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','nhvhhs']).
line(['$','ls']).
line(['92810','bgfgrzs']).
line(['$','cd','..']).
line(['$','cd','npclt']).
line(['$','ls']).
line(['dir','dcs']).
line(['dir','tsrqvpbq']).
line(['$','cd','dcs']).
line(['$','ls']).
line(['274856','nrqwg']).
line(['$','cd','..']).
line(['$','cd','tsrqvpbq']).
line(['$','ls']).
line(['144678','jlwjsbw.bzf']).
line(['dir','nqrdmvjm']).
line(['163728','qwddbflc.gjp']).
line(['$','cd','nqrdmvjm']).
line(['$','ls']).
line(['122069','btpm.vhg']).
line(['105752','psrmw']).
line(['149744','rvvjbz.bnn']).
line(['126434','ztdcrnl.hjj']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','rgdb']).
line(['$','ls']).
line(['75645','blzt']).
line(['dir','clz']).
line(['dir','ddmbzz']).
line(['dir','hrl']).
line(['280472','jgmd.htc']).
line(['217770','nqwgl.qqb']).
line(['dir','qjcrf']).
line(['$','cd','clz']).
line(['$','ls']).
line(['dir','fshcptjq']).
line(['125496','lhgsdhl.gss']).
line(['291857','pfbjptg.lqh']).
line(['78923','rdhmmqml.lrw']).
line(['$','cd','fshcptjq']).
line(['$','ls']).
line(['157704','btf']).
line(['66314','qcpjsfr']).
line(['225592','rsftvgr']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','ddmbzz']).
line(['$','ls']).
line(['217731','cbc.dmn']).
line(['16389','cdwwz']).
line(['256395','gwwh.ttt']).
line(['233481','rvsslvbh']).
line(['dir','rvvjbz']).
line(['dir','zgc']).
line(['$','cd','rvvjbz']).
line(['$','ls']).
line(['dir','zrwtdlzz']).
line(['$','cd','zrwtdlzz']).
line(['$','ls']).
line(['21488','gdgl.vbc']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','zgc']).
line(['$','ls']).
line(['222107','gwwh.ttt']).
line(['35382','npclt.fpp']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','hrl']).
line(['$','ls']).
line(['dir','rvvjbz']).
line(['$','cd','rvvjbz']).
line(['$','ls']).
line(['65335','dgn.mgd']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','qjcrf']).
line(['$','ls']).
line(['dir','fjrdgbwh']).
line(['$','cd','fjrdgbwh']).
line(['$','ls']).
line(['143960','wvnzt.wvq']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','wnb']).
line(['$','ls']).
line(['66543','jlwjsbw.bzf']).
line(['dir','nqrdmvjm']).
line(['dir','pfwptjtl']).
line(['3047','sbdlzbt.hlj']).
line(['$','cd','nqrdmvjm']).
line(['$','ls']).
line(['dir','cqn']).
line(['dir','mnmbmb']).
line(['182573','pmw.pdl']).
line(['dir','rvvjbz']).
line(['92911','ztdcrnl.hjj']).
line(['$','cd','cqn']).
line(['$','ls']).
line(['38563','npclt.pcl']).
line(['14353','sdlmtzzv']).
line(['52230','ztdcrnl.hjj']).
line(['$','cd','..']).
line(['$','cd','mnmbmb']).
line(['$','ls']).
line(['212337','fsjwz.css']).
line(['24700','gwwh.ttt']).
line(['10243','npclt']).
line(['dir','nqrdmvjm']).
line(['238617','rvvjbz']).
line(['$','cd','nqrdmvjm']).
line(['$','ls']).
line(['19026','plrvst.bpd']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','rvvjbz']).
line(['$','ls']).
line(['23115','fsjwz.css']).
line(['260656','jlwjsbw.bzf']).
line(['113097','zdrtjvzj.rlt']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','pfwptjtl']).
line(['$','ls']).
line(['134817','jlwjsbw.bzf']).
line(['80522','npclt']).
line(['254529','nqrdmvjm.mbc']).
line(['35322','ztdcrnl.hjj']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','hmw']).
line(['$','ls']).
line(['dir','cfc']).
line(['dir','cmbtwjqm']).
line(['dir','dsm']).
line(['81077','dzsj.bsl']).
line(['dir','gzgr']).
line(['dir','jrdhssrz']).
line(['dir','npclt']).
line(['dir','tsrqvpbq']).
line(['dir','vssgzdw']).
line(['dir','wngccwdr']).
line(['5928','wrpd.zwq']).
line(['113540','ztdcrnl.hjj']).
line(['$','cd','cfc']).
line(['$','ls']).
line(['159334','npclt']).
line(['212665','ztdcrnl.hjj']).
line(['$','cd','..']).
line(['$','cd','cmbtwjqm']).
line(['$','ls']).
line(['dir','vzftvhhc']).
line(['$','cd','vzftvhhc']).
line(['$','ls']).
line(['86763','jlwjsbw.bzf']).
line(['dir','nbj']).
line(['dir','qzbf']).
line(['$','cd','nbj']).
line(['$','ls']).
line(['63776','jlwjsbw.bzf']).
line(['$','cd','..']).
line(['$','cd','qzbf']).
line(['$','ls']).
line(['189850','rtszjp.zhq']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','dsm']).
line(['$','ls']).
line(['dir','bddwfjhv']).
line(['258304','fltv']).
line(['4285','jlwjsbw.bzf']).
line(['dir','nqrdmvjm']).
line(['dir','rvvjbz']).
line(['258902','zdrtjvzj.rlt']).
line(['$','cd','bddwfjhv']).
line(['$','ls']).
line(['201408','zdrtjvzj.rlt']).
line(['$','cd','..']).
line(['$','cd','nqrdmvjm']).
line(['$','ls']).
line(['250981','npclt.dnd']).
line(['$','cd','..']).
line(['$','cd','rvvjbz']).
line(['$','ls']).
line(['181444','npclt.msj']).
line(['146533','thzv.jbn']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','gzgr']).
line(['$','ls']).
line(['dir','brmzzz']).
line(['dir','dsm']).
line(['$','cd','brmzzz']).
line(['$','ls']).
line(['40671','jlwjsbw.bzf']).
line(['$','cd','..']).
line(['$','cd','dsm']).
line(['$','ls']).
line(['53299','bmdpw']).
line(['dir','npclt']).
line(['223542','qdrlng']).
line(['dir','thjnrtq']).
line(['$','cd','npclt']).
line(['$','ls']).
line(['30938','bdldl']).
line(['36847','gfwbhj.nvh']).
line(['159051','qjpggrst.czp']).
line(['233569','vwpr.drg']).
line(['dir','wwln']).
line(['$','cd','wwln']).
line(['$','ls']).
line(['153489','fsjwz.css']).
line(['196950','lzcrjs']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','thjnrtq']).
line(['$','ls']).
line(['30861','fsjwz.css']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','jrdhssrz']).
line(['$','ls']).
line(['194556','bqcn.ctq']).
line(['dir','gnhc']).
line(['148157','gwwh.ttt']).
line(['dir','jcqcjbj']).
line(['245407','jlwjsbw.bzf']).
line(['248457','lmvh']).
line(['$','cd','gnhc']).
line(['$','ls']).
line(['183841','fsjwz.css']).
line(['128648','hzcpmz']).
line(['154895','mvznln']).
line(['193794','ztdcrnl.hjj']).
line(['$','cd','..']).
line(['$','cd','jcqcjbj']).
line(['$','ls']).
line(['266176','cbbfjsp']).
line(['dir','dsm']).
line(['195555','sfq']).
line(['$','cd','dsm']).
line(['$','ls']).
line(['13098','bjhsqfpp.rvw']).
line(['dir','grpp']).
line(['dir','nqb']).
line(['$','cd','grpp']).
line(['$','ls']).
line(['259797','jvw.psl']).
line(['32317','sfm.twr']).
line(['$','cd','..']).
line(['$','cd','nqb']).
line(['$','ls']).
line(['82426','rvvjbz.fdm']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','npclt']).
line(['$','ls']).
line(['dir','tqzmprzr']).
line(['$','cd','tqzmprzr']).
line(['$','ls']).
line(['278120','dsm.hqd']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','tsrqvpbq']).
line(['$','ls']).
line(['dir','dqbnbl']).
line(['dir','dsm']).
line(['dir','lsglr']).
line(['213028','rvvjbz.rvh']).
line(['112991','tsrqvpbq.ptw']).
line(['$','cd','dqbnbl']).
line(['$','ls']).
line(['dir','dhzs']).
line(['281375','dsm']).
line(['121452','gwwh.ttt']).
line(['dir','mbc']).
line(['dir','npclt']).
line(['211213','tsrqvpbq.zsz']).
line(['125518','zdrtjvzj.rlt']).
line(['$','cd','dhzs']).
line(['$','ls']).
line(['110840','gwwh.ttt']).
line(['197645','tsrqvpbq']).
line(['$','cd','..']).
line(['$','cd','mbc']).
line(['$','ls']).
line(['224503','drsrlls.ctp']).
line(['dir','dzm']).
line(['65461','jlwjsbw.bzf']).
line(['dir','nqrdmvjm']).
line(['137158','nqrdmvjm.vtq']).
line(['dir','rvvjbz']).
line(['126868','rwrzljq']).
line(['$','cd','dzm']).
line(['$','ls']).
line(['279593','fsjwz.css']).
line(['13111','gwwh.ttt']).
line(['205453','hchlb.bdn']).
line(['277556','jlwjsbw.bzf']).
line(['dir','jvd']).
line(['dir','nqrdmvjm']).
line(['dir','prqlqh']).
line(['dir','rhdhhfs']).
line(['dir','rvvjbz']).
line(['$','cd','jvd']).
line(['$','ls']).
line(['76776','fsjwz.css']).
line(['85847','wqdzvs.vwf']).
line(['$','cd','..']).
line(['$','cd','nqrdmvjm']).
line(['$','ls']).
line(['40200','npclt.fcq']).
line(['$','cd','..']).
line(['$','cd','prqlqh']).
line(['$','ls']).
line(['267371','fsjwz.css']).
line(['$','cd','..']).
line(['$','cd','rhdhhfs']).
line(['$','ls']).
line(['51224','dsm.qln']).
line(['$','cd','..']).
line(['$','cd','rvvjbz']).
line(['$','ls']).
line(['dir','npclt']).
line(['dir','wdhgmfb']).
line(['60599','wjwgrq']).
line(['$','cd','npclt']).
line(['$','ls']).
line(['138588','bdqtq.slq']).
line(['221322','rjmbd.pdj']).
line(['279540','ztdcrnl.hjj']).
line(['$','cd','..']).
line(['$','cd','wdhgmfb']).
line(['$','ls']).
line(['98271','jcg.pwz']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','nqrdmvjm']).
line(['$','ls']).
line(['221950','swnsstls.zcl']).
line(['7947','tqwhs']).
line(['$','cd','..']).
line(['$','cd','rvvjbz']).
line(['$','ls']).
line(['272797','zdrtjvzj.rlt']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','npclt']).
line(['$','ls']).
line(['294537','bqlgnwwf.qqf']).
line(['285887','flzmnmft']).
line(['3041','fsjwz.css']).
line(['dir','npclt']).
line(['dir','rvvjbz']).
line(['235966','zhwvl']).
line(['$','cd','npclt']).
line(['$','ls']).
line(['96669','sjcr.qmc']).
line(['$','cd','..']).
line(['$','cd','rvvjbz']).
line(['$','ls']).
line(['240351','fsjwz.css']).
line(['112539','rvvjbz.tlc']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','dsm']).
line(['$','ls']).
line(['dir','dpbsq']).
line(['dir','lmvjnd']).
line(['dir','vjnb']).
line(['$','cd','dpbsq']).
line(['$','ls']).
line(['dir','vczm']).
line(['$','cd','vczm']).
line(['$','ls']).
line(['252709','jfzq.fvc']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','lmvjnd']).
line(['$','ls']).
line(['20118','rsp.njm']).
line(['$','cd','..']).
line(['$','cd','vjnb']).
line(['$','ls']).
line(['192558','vvggw.ljj']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','lsglr']).
line(['$','ls']).
line(['222728','qvp']).
line(['296718','ztdcrnl.hjj']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','vssgzdw']).
line(['$','ls']).
line(['dir','smfhgcv']).
line(['$','cd','smfhgcv']).
line(['$','ls']).
line(['16174','dtpgsvfv.csm']).
line(['43403','lhbqdpv']).
line(['dir','ndh']).
line(['52985','pcj.csh']).
line(['81157','vwsrt']).
line(['278111','zdrtjvzj.rlt']).
line(['$','cd','ndh']).
line(['$','ls']).
line(['80287','jlwjsbw.bzf']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','wngccwdr']).
line(['$','ls']).
line(['6088','ppjnslg']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','jhmrn']).
line(['$','ls']).
line(['dir','qwqhhbth']).
line(['$','cd','qwqhhbth']).
line(['$','ls']).
line(['dir','ggfmlp']).
line(['dir','qgflbldg']).
line(['$','cd','ggfmlp']).
line(['$','ls']).
line(['35739','dsm']).
line(['38351','jlwjsbw.bzf']).
line(['$','cd','..']).
line(['$','cd','qgflbldg']).
line(['$','ls']).
line(['dir','pbw']).
line(['dir','rvvjbz']).
line(['dir','tqppnqmv']).
line(['$','cd','pbw']).
line(['$','ls']).
line(['dir','nqrdmvjm']).
line(['5912','nqrdmvjm.qvj']).
line(['$','cd','nqrdmvjm']).
line(['$','ls']).
line(['dir','tnd']).
line(['$','cd','tnd']).
line(['$','ls']).
line(['dir','lwsvwsl']).
line(['$','cd','lwsvwsl']).
line(['$','ls']).
line(['150503','jlwjsbw.bzf']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','rvvjbz']).
line(['$','ls']).
line(['dir','dmrff']).
line(['dir','ssnbl']).
line(['dir','zgrgt']).
line(['$','cd','dmrff']).
line(['$','ls']).
line(['dir','vmmzmf']).
line(['$','cd','vmmzmf']).
line(['$','ls']).
line(['211105','tsrqvpbq']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','ssnbl']).
line(['$','ls']).
line(['246210','mlj.qbv']).
line(['$','cd','..']).
line(['$','cd','zgrgt']).
line(['$','ls']).
line(['207409','lnvqlhsj']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','tqppnqmv']).
line(['$','ls']).
line(['59007','gwwh.ttt']).
line(['123705','jlwjsbw.bzf']).
line(['277423','rvvjbz.hbn']).
line(['170157','tbs']).
line(['dir','ztg']).
line(['$','cd','ztg']).
line(['$','ls']).
line(['8432','fsjwz.css']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','ncb']).
line(['$','ls']).
line(['30859','dsm']).
line(['74337','jvp.jwl']).
line(['dir','lgvwz']).
line(['150310','lhl.rtq']).
line(['$','cd','lgvwz']).
line(['$','ls']).
line(['105307','fftbgl.tnh']).
line(['69432','npclt.sdq']).
line(['49765','zdrtjvzj.rlt']).
line(['214149','ztdcrnl.hjj']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','npclt']).
line(['$','ls']).
line(['dir','dsm']).
line(['dir','rvvjbz']).
line(['dir','trr']).
line(['$','cd','dsm']).
line(['$','ls']).
line(['dir','bcccgpl']).
line(['dir','cvddqch']).
line(['210401','fsjwz.css']).
line(['96482','nqrdmvjm.tgr']).
line(['dir','nwctzch']).
line(['29453','zdrtjvzj.rlt']).
line(['$','cd','bcccgpl']).
line(['$','ls']).
line(['237918','dshtjdcs']).
line(['dir','mtrcfbf']).
line(['dir','tgt']).
line(['dir','tsrqvpbq']).
line(['99779','wpfsbnh.nbh']).
line(['257112','ztdcrnl.hjj']).
line(['$','cd','mtrcfbf']).
line(['$','ls']).
line(['dir','hms']).
line(['49756','tsrqvpbq']).
line(['$','cd','hms']).
line(['$','ls']).
line(['185755','zdrtjvzj.rlt']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','tgt']).
line(['$','ls']).
line(['dir','dsm']).
line(['dir','jmfdpdf']).
line(['256858','zdrtjvzj.rlt']).
line(['$','cd','dsm']).
line(['$','ls']).
line(['71528','dsm.rvc']).
line(['$','cd','..']).
line(['$','cd','jmfdpdf']).
line(['$','ls']).
line(['231263','hgsvvrqt.vbp']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','tsrqvpbq']).
line(['$','ls']).
line(['218774','clhqvp']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','cvddqch']).
line(['$','ls']).
line(['144164','fsjwz.css']).
line(['dir','gfszp']).
line(['60880','nqrdmvjm']).
line(['222198','vhhtgj']).
line(['$','cd','gfszp']).
line(['$','ls']).
line(['127091','fsjwz.css']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','nwctzch']).
line(['$','ls']).
line(['258292','rfvvc']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','rvvjbz']).
line(['$','ls']).
line(['dir','cnv']).
line(['dir','dtpswgq']).
line(['dir','ggdhw']).
line(['97538','jsjlq']).
line(['218535','nqrdmvjm.fhj']).
line(['134022','tsrqvpbq.mbs']).
line(['51273','zdrtjvzj.rlt']).
line(['$','cd','cnv']).
line(['$','ls']).
line(['208016','gzvmv.dfg']).
line(['$','cd','..']).
line(['$','cd','dtpswgq']).
line(['$','ls']).
line(['dir','jfbgfts']).
line(['$','cd','jfbgfts']).
line(['$','ls']).
line(['273657','bbtbqv']).
line(['77349','dsm.rnc']).
line(['dir','nqrdmvjm']).
line(['208448','zdrtjvzj.rlt']).
line(['$','cd','nqrdmvjm']).
line(['$','ls']).
line(['dir','bjdrqnt']).
line(['dir','msqc']).
line(['dir','npclt']).
line(['dir','rsms']).
line(['dir','vzhdtv']).
line(['$','cd','bjdrqnt']).
line(['$','ls']).
line(['103077','tph.bpz']).
line(['264222','wmvzc']).
line(['$','cd','..']).
line(['$','cd','msqc']).
line(['$','ls']).
line(['72288','ztdcrnl.hjj']).
line(['$','cd','..']).
line(['$','cd','npclt']).
line(['$','ls']).
line(['dir','tfbzdm']).
line(['$','cd','tfbzdm']).
line(['$','ls']).
line(['dir','nqrdmvjm']).
line(['35970','nqrdmvjm.gwj']).
line(['54275','rvvjbz.pvs']).
line(['dir','wwrsrmn']).
line(['179618','ztdcrnl.hjj']).
line(['$','cd','nqrdmvjm']).
line(['$','ls']).
line(['dir','gljgj']).
line(['$','cd','gljgj']).
line(['$','ls']).
line(['135000','gwwh.ttt']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','wwrsrmn']).
line(['$','ls']).
line(['17120','npclt.vhz']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','rsms']).
line(['$','ls']).
line(['198169','fsjwz.css']).
line(['$','cd','..']).
line(['$','cd','vzhdtv']).
line(['$','ls']).
line(['234619','gwwh.ttt']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','ggdhw']).
line(['$','ls']).
line(['dir','dsm']).
line(['dir','fmljfpfb']).
line(['dir','nqrdmvjm']).
line(['dir','qrhnjrn']).
line(['dir','vpsqmmp']).
line(['$','cd','dsm']).
line(['$','ls']).
line(['185390','rvvjbz.ljl']).
line(['70843','scrzhct.shj']).
line(['dir','zqd']).
line(['$','cd','zqd']).
line(['$','ls']).
line(['197478','lrpnc.pqp']).
line(['dir','nljssvvw']).
line(['228126','rfsnv']).
line(['dir','wzvvggdp']).
line(['$','cd','nljssvvw']).
line(['$','ls']).
line(['248489','dwdcnzb.ztq']).
line(['$','cd','..']).
line(['$','cd','wzvvggdp']).
line(['$','ls']).
line(['40266','jlwjsbw.bzf']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','fmljfpfb']).
line(['$','ls']).
line(['dir','chc']).
line(['232964','gwwh.ttt']).
line(['283351','jlwjsbw.bzf']).
line(['$','cd','chc']).
line(['$','ls']).
line(['273399','cjtznvrq.jcd']).
line(['250531','dsm.djs']).
line(['dir','lgqz']).
line(['173885','pmlw.hcb']).
line(['273356','swwzbpdm']).
line(['7329','wtvs.qrr']).
line(['$','cd','lgqz']).
line(['$','ls']).
line(['9432','fst.nlb']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','nqrdmvjm']).
line(['$','ls']).
line(['129926','zdrtjvzj.rlt']).
line(['$','cd','..']).
line(['$','cd','qrhnjrn']).
line(['$','ls']).
line(['dir','vnvchpr']).
line(['dir','zchcq']).
line(['271220','ztdcrnl.hjj']).
line(['$','cd','vnvchpr']).
line(['$','ls']).
line(['257931','rvvjbz']).
line(['132252','wtgs.btb']).
line(['$','cd','..']).
line(['$','cd','zchcq']).
line(['$','ls']).
line(['dir','hmf']).
line(['215104','sshml']).
line(['$','cd','hmf']).
line(['$','ls']).
line(['253334','gbvbmwbf.lhs']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','vpsqmmp']).
line(['$','ls']).
line(['32455','gwwh.ttt']).
line(['170338','rfsvs.dfq']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','trr']).
line(['$','ls']).
line(['dir','bfjwfd']).
line(['dir','bhrvh']).
line(['dir','ggfc']).
line(['187910','gwwh.ttt']).
line(['dir','mtqftj']).
line(['$','cd','bfjwfd']).
line(['$','ls']).
line(['dir','npclt']).
line(['dir','wqqfszn']).
line(['$','cd','npclt']).
line(['$','ls']).
line(['269520','trrcw.jmq']).
line(['$','cd','..']).
line(['$','cd','wqqfszn']).
line(['$','ls']).
line(['151594','rvvjbz.gvt']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','bhrvh']).
line(['$','ls']).
line(['251782','cpbvqrjj']).
line(['$','cd','..']).
line(['$','cd','ggfc']).
line(['$','ls']).
line(['65357','gwwh.ttt']).
line(['dir','jqjtwf']).
line(['$','cd','jqjtwf']).
line(['$','ls']).
line(['65025','wzrp.pbp']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','mtqftj']).
line(['$','ls']).
line(['294942','vtjhwjr.qgc']).
line(['88168','wvbnjp.blf']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','..']).
line(['$','cd','rvvjbz']).
line(['$','ls']).
line(['dir','csfp']).
line(['141875','dsm']).
line(['294580','jlwjsbw.bzf']).
line(['dir','jqlm']).
line(['25928','lqhpn.jrh']).
line(['224295','zdrtjvzj.rlt']).
line(['113314','zww.ftt']).
line(['$','cd','csfp']).
line(['$','ls']).
line(['153717','ztdcrnl.hjj']).
line(['$','cd','..']).
line(['$','cd','jqlm']).
line(['$','ls']).
line(['163455','jlwjsbw.bzf']).
