stack(1,['R','H','M','P','Z']).
stack(2,['B','J','C','P']).
stack(3,['D','C','L','G','H','N','S']).
stack(4,['L','R','S','Q','D','M','T','F']).
stack(5,['M','Z','T','B','Q','P','S','F']).
stack(6,['G','B','Z','S','F','T']).
stack(7,['V','R','N']).
stack(8,['M','C','V','D','T','L','G','P']).
stack(9,['L','M','F','J','N','Q','W']).